
# C++ project
language: cpp

# Only build master and tags
if: branch = master OR tag IS present

git:
    submodules: true

env:
  global:
    # Bintray
    - BINTRAY_USER=manromen
    # BINTRAY_KEY
    - secure: "wE52pK3O6WvG4Gsmd3q8i3dcANY/B7BEFIUDa4CtqQfyoFaLkZVi/WscDAwmCxw3XUNbxrwa/gFlEjsOtr4Fob4NPN0KaZKl3ilsVp49pYEzLGoDNYipr4EwuUbIQaBKkuTlm96W93LLT7Lw6TY6XeBGHvKAdYClqTGiNWBt3cxUf1fYdwvLAvsbzVG84f9zokttzK9EwEa+/k2yq7OCuDIIhabPQtCJIT9+8Epc4yxjJM35Sq404t3KGoiYmiG8x123jo5qsQqwQnLK+HYjhUpomHnTPQBci7J2WOP6idzkNRANJlH8C443lkuAR1bge7ETxAkaWp3yJ8h1RjJwzeK028M8+u1dxD/ji/yj++NDsrFyiOJZDdjqz/q3jZRw/0zTGR4YRKQktQjfebxga/Wa8lZ7NTu0nVuqSYVZ2KZkwdrukww2lEAvxXYoOO9FbESe2Qf+XmnWA63etw6jf7c1Qg4JUT4kSgZuiRjVpXpxqUw930cvESxzk++bqNBLQLn4SIL3n8BUZWF3XPNk2eZoUHR3cDUv0puvdCIHQpvyYhp27ncNaq3jrsYBjYko0N0MWJv3WXPpiPM+pecm9BDs3hfAQgqTv36EANLb2eByPQBHUXimhpG0Yq1cwk/MZGBFfPxFqR3UiW8HDxuEncbeX1zBhLS8mOzMkIlVRQ4="
    
    # Conan
    - CONAN_REPOSITORY=https://api.bintray.com/conan/manromen/rgpaul
    - CONAN_REPOSITORY_NAME=rgpaul
    - CONAN_USER=rgpaul
    - CONAN_CHANNEL=stable
    - CONAN_LIBRARY_VERSION=470
    - CONAN_PACKAGE_NAME=djinni

    # Maven
    - TRAVIS_MAVEN_SERVER_ID=rgpaul-mvn
    - TRAVIS_MAVEN_USER=manromen
    # TRAVIS_MAVEN_PWD
    - secure: "HD5PYsdDngyz5iDeqcvtCFq6mbss4LCrjitj2IUUCPo/UlFXfoD1/4JEF55NZQBRBKS4G5aFe5NpggLGsExRyvPBLLZLy+xGo7Ij1EyK7WQ3FjjF/caHgS1ekvOGhQzaZ14g59ij2f4UWvjWuC6qpdJs17YnsMYgD2X0s//x7sdIkeIAUhajPzPw5U9KaJkBgiad4JbvlJM3S3pp2rEbGc/gkkIsohMeyoaS2kWb+tAz7NMNoLGX8LRydX8D3W+PJLdIrbULmR615HW2+asOWxwNWa/vXDvIxMfV6BbgiIbvtoyPksTmcv/p08JSMxMuh3DJhqz/AIvPHCTu6I8jb8krGCozQr1uWOJeC7P0XD55ptW9A3a6hPatQmRxlEdebZu/YPyLi0FVawi8rL8Uq77KiE3DK5H9S0rm2a4L6EUlbpbgCfJF/Un6maPdqX9RzFUGvWWmBvUmUMazxjjKLuz2eYtdyWIYFoCUvAuGltj7GHaxuBBHrrjmCd58NMal8UL2bPs5x4LvVWnsuPDr7+1CWKVoRncN2HdPgH1Q5A+zra/+DEUIRedhrYXa2qcUWxlmvfwgGj/OMxSantFs2sNH5boC+3suj/5SCbSUS2zAHXa8tQRfvHZhHRNOTcXKlr9/9TmT2RYqFkG419MH3hO+NdCdCUra8z26EdP7/ls="
    - TRAVIS_MAVEN_URL=https://api.bintray.com/maven/manromen/rgpaul-mvn/djinni
    - TRAVIS_MAVEN_GROUP_ID=com.rgpaul
    - TRAVIS_MAVEN_ARTIFACT_ID=djinni
    - TRAVIS_MAVEN_VERSION=${CONAN_LIBRARY_VERSION}-${TRAVIS_BUILD_NUMBER}
    - TRAVIS_MAVEN_FILE=djinni.jar
    - TRAVIS_MAVEN_ARTIFACT="com.rgpaul:djinni:${TRAVIS_MAVEN_VERSION}"

### before installing deps
before_install:
  # Download Android NDK from Google
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$TARGET_PLATFORM" == "android" ]]; then
      curl -sSOL "https://dl.google.com/android/repository/android-ndk-${TRAVIS_ANDROID_NDK_VERSION}-linux-x86_64.zip";
      unzip -q -o android-ndk-${TRAVIS_ANDROID_NDK_VERSION}-linux-x86_64.zip;
      export ANDROID_NDK_PATH=${TRAVIS_BUILD_DIR}/android-ndk-${TRAVIS_ANDROID_NDK_VERSION};
    fi

### install deps
install:

    # Install conan (linux)
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      pip install conan --user;
    fi

  # Install conan (macos)
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      pip3 install conan;
    fi

  # Add conan repository and apply conan config
  - conan remote add ${CONAN_REPOSITORY_NAME} ${CONAN_REPOSITORY}
  - conan config install ${TRAVIS_BUILD_DIR}/.travis/conan/config.zip

  # login to conan
  - conan user -p "$BINTRAY_KEY" -r ${CONAN_REPOSITORY_NAME} ${BINTRAY_USER}

  # install java, sbt and maven via sdkman.io
  - if [ "$TARGET_PLATFORM" == "djinni_jar" ]; then
      curl -s "https://get.sdkman.io" | bash;
      source "${HOME}/.sdkman/bin/sdkman-init.sh";
      sdk install java;
      sdk install sbt;
      sdk install maven;
    fi

  - if [ "$TARGET_PLATFORM" != "djinni_jar" ]; then
      bash .travis/provider/maven-download-file.sh;
    fi

### build script
script:
  # show OS/compiler version
  - uname -a

  # make sure CXX is correctly set
  - if [[ "${COMPILER}" != "" ]]; then export CXX=${COMPILER}; fi

  # Android Builds (shared and static)
  - if [ "$TARGET_PLATFORM" == "android" ]; then
      conan create . ${CONAN_PACKAGE_NAME}/${CONAN_LIBRARY_VERSION}@${CONAN_USER}/${CONAN_CHANNEL} -s os=Android -s os.api_level=${TRAVIS_ANDROID_API_LEVEL} -s compiler=${TRAVIS_ANDROID_COMPILER} -s compiler.version=${TRAVIS_ANDROID_COMPILER_VERSION} -s compiler.libcxx=${TRAVIS_ANDROID_COMPILER_LIBCXX} -s build_type=${TARGET_BUILD_TYPE} -o android_ndk=${TRAVIS_ANDROID_NDK_VERSION} -o android_stl_type=${TRAVIS_ANDROID_STL_TYPE} -s arch=${TRAVIS_ANDROID_ARCH} -o shared=False;
      conan create . ${CONAN_PACKAGE_NAME}/${CONAN_LIBRARY_VERSION}@${CONAN_USER}/${CONAN_CHANNEL} -s os=Android -s os.api_level=${TRAVIS_ANDROID_API_LEVEL} -s compiler=${TRAVIS_ANDROID_COMPILER} -s compiler.version=${TRAVIS_ANDROID_COMPILER_VERSION} -s compiler.libcxx=${TRAVIS_ANDROID_COMPILER_LIBCXX} -s build_type=${TARGET_BUILD_TYPE} -o android_ndk=${TRAVIS_ANDROID_NDK_VERSION} -o android_stl_type=${TRAVIS_ANDROID_STL_TYPE} -s arch=${TRAVIS_ANDROID_ARCH} -o shared=True;
    fi

  # iOS Builds
  - if [ "$TARGET_PLATFORM" == "ios" ]; then
      export IOS_SDK_VERSION=$(xcodebuild -showsdks | grep iphoneos | awk '{print $4}' | sed 's/[^0-9,\.]*//g');
      echo "iOS SDK ${IOS_SDK_VERSION}";
      conan create . ${CONAN_PACKAGE_NAME}/${CONAN_LIBRARY_VERSION}@${CONAN_USER}/${CONAN_CHANNEL} -s os=iOS -s os.version=${IOS_SDK_VERSION} -s arch=${TARGET_ARCH} -s build_type=${TARGET_BUILD_TYPE} -o shared=False;
    fi

  # build the djinni fat file
  - if [ "$TARGET_PLATFORM" == "djinni_jar" ]; then
      cd djinni;
      make djinni_jar;
      cp src/target/scala-2.11/src-assembly-0.1-SNAPSHOT.jar ${TRAVIS_BUILD_DIR}/djinni.jar;
      cd ${TRAVIS_BUILD_DIR};
    fi

after_success:
  - if [ "$TARGET_PLATFORM" == "djinni_jar" ]; then
      bash .travis/provider/maven-upload-file.sh;
    fi

deploy:
  provider: script
  script: bash .travis/provider/conan-deploy.sh
  on:
    tags: true
    condition: $TARGET_PLATFORM != djinni_jar

stages:
  - jar
  - library

### build matrix
matrix:
  include:
    
    # djinni_jar
    - stage: jar
      os: linux
      dist: xenial # Ubuntu 16.04 (Xenial)
      env:
        - TARGET_PLATFORM=djinni_jar
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-5' ]

    # iOS - Release
    - stage: library
      os: osx
      osx_image: xcode10.2
      compiler: clang
      env:
        - TARGET_PLATFORM=ios
        - TARGET_ARCH=armv8
        - TARGET_BUILD_TYPE=Release

    # iOS - Debug
    - stage: library
      os: osx
      osx_image: xcode10.2
      compiler: clang
      env:
        - TARGET_PLATFORM=ios
        - TARGET_ARCH=armv8
        - TARGET_BUILD_TYPE=Debug

    # iOS - Simulator
    - stage: library
      os: osx
      osx_image: xcode10.2
      compiler: clang
      env:
        - TARGET_PLATFORM=ios
        - TARGET_ARCH=x86_64
        - TARGET_BUILD_TYPE=Debug

    ### Android NDK r20 - arm64-v8a ###
    - stage: library
      os: linux
      dist: xenial # Ubuntu 16.04 (Xenial)
      env:
        - TARGET_PLATFORM=android
        - TRAVIS_ANDROID_NDK_VERSION=r20
        - TRAVIS_ANDROID_COMPILER=clang
        - TRAVIS_ANDROID_COMPILER_VERSION=8.0
        - TRAVIS_ANDROID_ARCH=armv8
        - TRAVIS_ANDROID_API_LEVEL=21
        - TRAVIS_ANDROID_COMPILER_LIBCXX=libc++
        - TRAVIS_ANDROID_STL_TYPE=c++_static
        - TARGET_BUILD_TYPE=Release
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-5' ]

    ### Android NDK r20 - armeabi-v7a ###
    - stage: library
      os: linux
      dist: xenial # Ubuntu 16.04 (Xenial)
      env:
        - TARGET_PLATFORM=android
        - TRAVIS_ANDROID_NDK_VERSION=r20
        - TRAVIS_ANDROID_COMPILER=clang
        - TRAVIS_ANDROID_COMPILER_VERSION=8.0
        - TRAVIS_ANDROID_ARCH=armv7
        - TRAVIS_ANDROID_API_LEVEL=19
        - TRAVIS_ANDROID_COMPILER_LIBCXX=libc++
        - TRAVIS_ANDROID_STL_TYPE=c++_static
        - TARGET_BUILD_TYPE=Release
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-5' ]

    ### Android NDK r20 - x86 ###
    - stage: library
      os: linux
      dist: xenial # Ubuntu 16.04 (Xenial)
      env:
        - TARGET_PLATFORM=android
        - TRAVIS_ANDROID_NDK_VERSION=r20
        - TRAVIS_ANDROID_COMPILER=clang
        - TRAVIS_ANDROID_COMPILER_VERSION=8.0
        - TRAVIS_ANDROID_ARCH=x86
        - TRAVIS_ANDROID_API_LEVEL=19
        - TRAVIS_ANDROID_COMPILER_LIBCXX=libc++
        - TRAVIS_ANDROID_STL_TYPE=c++_static
        - TARGET_BUILD_TYPE=Release
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-5' ]

    ### Android NDK r20 - x86_64 ###
    - stage: library
      os: linux
      dist: xenial # Ubuntu 16.04 (Xenial)
      env:
        - TARGET_PLATFORM=android
        - TRAVIS_ANDROID_NDK_VERSION=r20
        - TRAVIS_ANDROID_COMPILER=clang
        - TRAVIS_ANDROID_COMPILER_VERSION=8.0
        - TRAVIS_ANDROID_ARCH=x86_64
        - TRAVIS_ANDROID_API_LEVEL=21
        - TRAVIS_ANDROID_COMPILER_LIBCXX=libc++
        - TRAVIS_ANDROID_STL_TYPE=c++_static
        - TARGET_BUILD_TYPE=Release
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-5' ]

    ### Android NDK r19c - arm64-v8a ###
    - stage: library
      os: linux
      dist: xenial # Ubuntu 16.04 (Xenial)
      env:
        - TARGET_PLATFORM=android
        - TRAVIS_ANDROID_NDK_VERSION=r19c
        - TRAVIS_ANDROID_COMPILER=clang
        - TRAVIS_ANDROID_COMPILER_VERSION=8.0
        - TRAVIS_ANDROID_ARCH=armv8
        - TRAVIS_ANDROID_API_LEVEL=21
        - TRAVIS_ANDROID_COMPILER_LIBCXX=libc++
        - TRAVIS_ANDROID_STL_TYPE=c++_static
        - TARGET_BUILD_TYPE=Release
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-5' ]

    ### Android NDK r19c - armeabi-v7a ###
    - stage: library
      os: linux
      dist: xenial # Ubuntu 16.04 (Xenial)
      env:
        - TARGET_PLATFORM=android
        - TRAVIS_ANDROID_NDK_VERSION=r19c
        - TRAVIS_ANDROID_COMPILER=clang
        - TRAVIS_ANDROID_COMPILER_VERSION=8.0
        - TRAVIS_ANDROID_ARCH=armv7
        - TRAVIS_ANDROID_API_LEVEL=19
        - TRAVIS_ANDROID_COMPILER_LIBCXX=libc++
        - TRAVIS_ANDROID_STL_TYPE=c++_static
        - TARGET_BUILD_TYPE=Release
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-5' ]

    ### Android NDK r19c - x86 ###
    - stage: library
      os: linux
      dist: xenial # Ubuntu 16.04 (Xenial)
      env:
        - TARGET_PLATFORM=android
        - TRAVIS_ANDROID_NDK_VERSION=r19c
        - TRAVIS_ANDROID_COMPILER=clang
        - TRAVIS_ANDROID_COMPILER_VERSION=8.0
        - TRAVIS_ANDROID_ARCH=x86
        - TRAVIS_ANDROID_API_LEVEL=19
        - TRAVIS_ANDROID_COMPILER_LIBCXX=libc++
        - TRAVIS_ANDROID_STL_TYPE=c++_static
        - TARGET_BUILD_TYPE=Release
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-5' ]

    ### Android NDK r19c - x86_64 ###
    - stage: library
      os: linux
      dist: xenial # Ubuntu 16.04 (Xenial)
      env:
        - TARGET_PLATFORM=android
        - TRAVIS_ANDROID_NDK_VERSION=r19c
        - TRAVIS_ANDROID_COMPILER=clang
        - TRAVIS_ANDROID_COMPILER_VERSION=8.0
        - TRAVIS_ANDROID_ARCH=x86_64
        - TRAVIS_ANDROID_API_LEVEL=21
        - TRAVIS_ANDROID_COMPILER_LIBCXX=libc++
        - TRAVIS_ANDROID_STL_TYPE=c++_static
        - TARGET_BUILD_TYPE=Release
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-5' ]

    ### Android NDK r16b - arm64-v8a ###
    - stage: library
      os: linux
      dist: xenial # Ubuntu 16.04 (Xenial)
      env:
        - TARGET_PLATFORM=android
        - TRAVIS_ANDROID_NDK_VERSION=r16b
        - TRAVIS_ANDROID_COMPILER=clang
        - TRAVIS_ANDROID_COMPILER_VERSION=5.0
        - TRAVIS_ANDROID_ARCH=armv8
        - TRAVIS_ANDROID_API_LEVEL=21
        - TRAVIS_ANDROID_COMPILER_LIBCXX=libc++
        - TRAVIS_ANDROID_STL_TYPE=c++_static
        - TARGET_BUILD_TYPE=Release
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-5' ]

    ### Android NDK r16b - armeabi-v7a ###
    - stage: library
      os: linux
      dist: xenial # Ubuntu 16.04 (Xenial)
      env:
        - TARGET_PLATFORM=android
        - TRAVIS_ANDROID_NDK_VERSION=r16b
        - TRAVIS_ANDROID_COMPILER=clang
        - TRAVIS_ANDROID_COMPILER_VERSION=5.0
        - TRAVIS_ANDROID_ARCH=armv7
        - TRAVIS_ANDROID_API_LEVEL=19
        - TRAVIS_ANDROID_COMPILER_LIBCXX=libc++
        - TRAVIS_ANDROID_STL_TYPE=c++_static
        - TARGET_BUILD_TYPE=Release
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-5' ]

    ### Android NDK r16b - x86 ###
    - stage: library
      os: linux
      dist: xenial # Ubuntu 16.04 (Xenial)
      env:
        - TARGET_PLATFORM=android
        - TRAVIS_ANDROID_NDK_VERSION=r16b
        - TRAVIS_ANDROID_COMPILER=clang
        - TRAVIS_ANDROID_COMPILER_VERSION=5.0
        - TRAVIS_ANDROID_ARCH=x86
        - TRAVIS_ANDROID_API_LEVEL=19
        - TRAVIS_ANDROID_COMPILER_LIBCXX=libc++
        - TRAVIS_ANDROID_STL_TYPE=c++_static
        - TARGET_BUILD_TYPE=Release
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-5' ]

    ### Android NDK r16b - x86_64 ###
    - stage: library
      os: linux
      dist: xenial # Ubuntu 16.04 (Xenial)
      env:
        - TARGET_PLATFORM=android
        - TRAVIS_ANDROID_NDK_VERSION=r16b
        - TRAVIS_ANDROID_COMPILER=clang
        - TRAVIS_ANDROID_COMPILER_VERSION=5.0
        - TRAVIS_ANDROID_ARCH=x86_64
        - TRAVIS_ANDROID_API_LEVEL=21
        - TRAVIS_ANDROID_COMPILER_LIBCXX=libc++
        - TRAVIS_ANDROID_STL_TYPE=c++_static
        - TARGET_BUILD_TYPE=Release
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-5' ]

    ### Android NDK r16b - mips ###
    - stage: library
      os: linux
      dist: xenial # Ubuntu 16.04 (Xenial)
      env:
        - TARGET_PLATFORM=android
        - TRAVIS_ANDROID_NDK_VERSION=r16b
        - TRAVIS_ANDROID_COMPILER=clang
        - TRAVIS_ANDROID_COMPILER_VERSION=5.0
        - TRAVIS_ANDROID_ARCH=mips
        - TRAVIS_ANDROID_API_LEVEL=19
        - TRAVIS_ANDROID_COMPILER_LIBCXX=libc++
        - TRAVIS_ANDROID_STL_TYPE=c++_static
        - TARGET_BUILD_TYPE=Release
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-5' ]

    ### Android NDK r16b - mips64 ###
    - stage: library
      os: linux
      dist: xenial # Ubuntu 16.04 (Xenial)
      env:
        - TARGET_PLATFORM=android
        - TRAVIS_ANDROID_NDK_VERSION=r16b
        - TRAVIS_ANDROID_COMPILER=clang
        - TRAVIS_ANDROID_COMPILER_VERSION=5.0
        - TRAVIS_ANDROID_ARCH=mips64
        - TRAVIS_ANDROID_API_LEVEL=21
        - TRAVIS_ANDROID_COMPILER_LIBCXX=libc++
        - TRAVIS_ANDROID_STL_TYPE=c++_static
        - TARGET_BUILD_TYPE=Release
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-5' ]
